// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a simplified version for compilation without protoc

package server

import "context"

// NodeFilter 节点过滤器
type NodeFilter struct {
	Capabilities []string
	Status       string
	Region       string
	Limit        int32
}

// NodeList 节点列表
type NodeList struct {
	Nodes []*NodeInfo
	Total int32
}

// NodeInfo 节点信息
type NodeInfo struct {
	NodeId       string
	PeerId       string
	Addresses    []string
	Status       string
	Capabilities []string
	ConnectedAt  int64
	LastSeen     int64
}

// NodeInfoRequest 节点信息请求
type NodeInfoRequest struct {
	NodeId string
}

// NodeInfoResponse 节点信息响应
type NodeInfoResponse struct {
	Node  *NodeInfo
	Found bool
}

// TaskRequest 任务请求
type TaskRequest struct {
	TaskId     string
	TaskType   string
	Payload    []byte
	TargetNode string
	TimeoutMs  int64
}

// TaskResponse 任务响应
type TaskResponse struct {
	TaskId     string
	Success    bool
	Result     []byte
	Error      string
	ExecutedBy string
	DurationMs int64
}

// DataRequest 数据存储请求
type DataRequest struct {
	Key        string
	Value      []byte
	TtlSeconds int64
}

// StoreResponse 存储响应
type StoreResponse struct {
	Success bool
	Key     string
	Error   string
}

// FetchRequest 数据获取请求
type FetchRequest struct {
	Key string
}

// FetchResponse 获取响应
type FetchResponse struct {
	Found bool
	Value []byte
	Error string
}

// HeartbeatRequest 心跳请求
type HeartbeatRequest struct {
	NodeId       string
	Status       string
	Capabilities []string
	Timestamp    int64
}

// HeartbeatResponse 心跳响应
type HeartbeatResponse struct {
	Success    bool
	ServerTime int64
}

// ToolNetworkServer 服务接口
type ToolNetworkServer interface {
	GetNodeList(ctx context.Context, filter *NodeFilter) (*NodeList, error)
	GetNodeInfo(ctx context.Context, req *NodeInfoRequest) (*NodeInfoResponse, error)
	SendTask(ctx context.Context, req *TaskRequest) (*TaskResponse, error)
	StoreData(ctx context.Context, req *DataRequest) (*StoreResponse, error)
	FetchData(ctx context.Context, req *FetchRequest) (*FetchResponse, error)
	Heartbeat(ctx context.Context, req *HeartbeatRequest) (*HeartbeatResponse, error)
}

// UnimplementedToolNetworkServer 未实现的服务
type UnimplementedToolNetworkServer struct{}

func (UnimplementedToolNetworkServer) GetNodeList(ctx context.Context, filter *NodeFilter) (*NodeList, error) {
	return nil, nil
}

func (UnimplementedToolNetworkServer) GetNodeInfo(ctx context.Context, req *NodeInfoRequest) (*NodeInfoResponse, error) {
	return nil, nil
}

func (UnimplementedToolNetworkServer) SendTask(ctx context.Context, req *TaskRequest) (*TaskResponse, error) {
	return nil, nil
}

func (UnimplementedToolNetworkServer) StoreData(ctx context.Context, req *DataRequest) (*StoreResponse, error) {
	return nil, nil
}

func (UnimplementedToolNetworkServer) FetchData(ctx context.Context, req *FetchRequest) (*FetchResponse, error) {
	return nil, nil
}

func (UnimplementedToolNetworkServer) Heartbeat(ctx context.Context, req *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, nil
}

// RegisterToolNetworkServer 注册服务
func RegisterToolNetworkServer(s interface{}, srv ToolNetworkServer) {
	// gRPC 注册逻辑会在实际生成代码中实现
}
